version: '3.8'
services:
  postgres:
    image: postgres:15
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - bookstore:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    container_name: bookstore-container
volumes:
  bookstore:
