version: '3.8'

services:
  bookstore:
    image: postgres:15
    restart: always
    container_name: bookstore
    ports:
      - '5432:5432'
    env_file:
      - .env

  bookstore-tests:
    image: postgres:15
    restart: always
    container_name: bookstore-tests
    ports:
      - '5433:5432'
    env_file:
      - .env.test

volumes:
  bookstore:
